/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.apimatic.examples.controllers;

import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.examples.ApiHelper;
import io.apimatic.examples.Server;
import io.apimatic.examples.exceptions.ApiException;
import io.apimatic.examples.http.request.HttpMethod;
import io.apimatic.examples.models.OperationTypeEnum;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class SimpleCalculatorController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public SimpleCalculatorController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Calculates the expression using the specified operation.
     * @param  operation  Required parameter: The operator to apply on the variables
     * @param  x  Required parameter: The LHS value
     * @param  y  Required parameter: The RHS value
     * @return    Returns the Double response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public Double getCalculate(
            final OperationTypeEnum operation,
            final double x,
            final double y) throws ApiException, IOException {
        return prepareGetCalculateRequest(operation, x, y).execute();
    }

    /**
     * Calculates the expression using the specified operation.
     * @param  operation  Required parameter: The operator to apply on the variables
     * @param  x  Required parameter: The LHS value
     * @param  y  Required parameter: The RHS value
     * @return    Returns the Double response from the API call
     */
    public CompletableFuture<Double> getCalculateAsync(
            final OperationTypeEnum operation,
            final double x,
            final double y) {
        try {
            return prepareGetCalculateRequest(operation, x, y).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getCalculate.
     */
    private ApiCall<Double, ApiException> prepareGetCalculateRequest(
            final OperationTypeEnum operation,
            final double x,
            final double y) {
        return new ApiCall.Builder<Double, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/{operation}")
                        .queryParam(param -> param.key("x")
                                .value(x).isRequired(false))
                        .queryParam(param -> param.key("y")
                                .value(y).isRequired(false))
                        .templateParam(param -> param.key("operation").value((operation != null) ? operation.value() : null)
                                .shouldEncode(true))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> Double.parseDouble(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}